name: CI

on:
  pull_request:
  push:
    branches: ['main', 'development']

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build project
        working-directory: './src'
        run: dotnet build
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: super
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Start postgres
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        working-directory: './src'
        run: dotnet build
      - name: Run tests
        working-directory: './src'
        run: dotnet test --no-build --verbosity normal
