name: CI

on:
  pull_request:
  push:
    branches: ['main', 'development']

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build project
        working-directory: './src'
        run: dotnet build
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: super
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build project
        working-directory: './src'
        run: dotnet test
