name: CI

on:
  pull_request:
  push:
    branches: ['main', 'development']

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build project
        working-directory: './src'
        run: dotnet build
