name: CI

on:
  pull_request:
  push:
    branches: ['main', 'development']

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build project
        working-directory: './src'
        run: dotnet build
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Start postgres
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Set up postgres credentials
        run: sudo -u postgres psql --command="CREATE USER postgres PASSWORD 'super'" --command="\du"
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Run tests
        working-directory: './src'
        run: dotnet test
